// src/app/api/documents/[id]/route.ts — [FIX A3] edit/delete documents
// Note: docNumber is generated by the system and is NOT editable here, so the
// per-office sequence stays intact.
import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { documentSchema } from "@/lib/enums";
import {
  requirePermission,
  officeScope,
  handleError,
  readJson,
  GuardError,
} from "@/lib/guard";

export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { session } = await requirePermission("documents", "edit");
    const { id } = await params;
    const docId = Number(id);
    if (!docId) throw new GuardError(400, "معرّف غير صالح");

    const body = await readJson(req);
    // direction is omitted from edits because changing it would desync the
    // OUT-/IN- numbering; document number stays fixed once issued.
    const parsed = documentSchema.partial().omit({ direction: true }).safeParse(body);
    if (!parsed.success) {
      return Response.json(
        { error: parsed.error.issues[0]?.message ?? "بيانات غير صالحة" },
        { status: 400 }
      );
    }

    const scope = officeScope(session);
    const existing = await db.document.findFirst({
      where: { id: docId, ...scope },
      select: { id: true },
    });
    if (!existing) throw new GuardError(404, "الكتاب غير موجود");

    const data: Record<string, unknown> = { ...parsed.data };
    delete (data as any).officeId;
    delete (data as any).docNumber;

    const document = await db.document.update({
      where: { id: docId },
      data,
    });
    return Response.json({ document });
  } catch (err) {
    return handleError(err);
  }
}

export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { session } = await requirePermission("documents", "full");
    const { id } = await params;
    const docId = Number(id);
    if (!docId) throw new GuardError(400, "معرّف غير صالح");

    const scope = officeScope(session);
    const existing = await db.document.findFirst({
      where: { id: docId, ...scope },
      select: { id: true },
    });
    if (!existing) throw new GuardError(404, "الكتاب غير موجود");

    await db.document.delete({ where: { id: docId } });
    return Response.json({ ok: true });
  } catch (err) {
    return handleError(err);
  }
}
